import pandas as pd
import numpy as np

def engineer_features(df):
    """
    Apply comprehensive feature engineering for a timeseries dataframe.
    Features: lags (1,2,3), moving averages (5,10,20), rolling calculations, momentum
    """
    # Ensure it's a dataframe
    if not isinstance(df, pd.DataFrame):
        raise ValueError("Input must be a pandas DataFrame")
        
    df = df.copy()
    
    # Needs a timestamp column to sort safely
    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_datetime(df['timestamp'], format='mixed', utc=True)
        df = df.sort_values(by=['ticker', 'timestamp'])
    
    # We group by ticker if multiple exist
    def add_features(group):
        # Lags
        group['lag1'] = group['price'].shift(1)
        group['lag2'] = group['price'].shift(2)
        group['lag3'] = group['price'].shift(3)
        
        # Moving Averages
        group['MA5'] = group['price'].rolling(window=5).mean()
        group['MA10'] = group['price'].rolling(window=10).mean()
        group['MA20'] = group['price'].rolling(window=20).mean()
        
        # Rolling Statistics
        group['rolling_mean'] = group['price'].rolling(window=5).mean() # Alias
        group['rolling_std'] = group['price'].rolling(window=5).std()
        
        # Momentum Indicators
        group['price_change'] = group['price'].diff()
        group['pct_change'] = group['price'].pct_change()
        
        # Target Variable (Predict price 5 steps ahead)
        group['target'] = group['price'].shift(-5)
        
        return group
        
    # Apply features per ticker robustly (avoids Pandas 3.x groupby-apply index dropping bugs)
    grouped_dfs = []
    for ticker_name, group in df.groupby('ticker'):
        grouped_dfs.append(add_features(group.copy()))
        
    df = pd.concat(grouped_dfs).reset_index(drop=True)
    
    # Drop rows with NaNs generated by shifting and rolling
    df = df.dropna()
    
    return df